import os

DEBUG = os.getenv("DEBUG", "false").lower() == "true"
SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_KEY = os.getenv("SUPABASE_KEY")
STRIPE_SECRET_KEY = os.getenv("STRIPE_SECRET_KEY")
STRIPE_PREMIUM_PRICE_ID = os.getenv("STRIPE_PREMIUM_PRICE_ID")
STRIPE_VIP_PRICE_ID = os.getenv("STRIPE_VIP_PRICE_ID")
STRIPE_WEBHOOK_SECRET = os.getenv("STRIPE_WEBHOOK_SECRET")
FIREBASE_PROJECT_ID = os.getenv("FIREBASE_PROJECT_ID")
FCM_CREDENTIALS_PATH = os.getenv("FCM_CREDENTIALS_PATH")
